{% set name = "matching" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 130d9e88661f623dc39e84675facee2ce2b192420a2f8c4f274a38393837a5de

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - matching
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/daffidwilde/matching
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A package for solving matching games.'
  description: |
    Matching games allow for the allocation of resources and partnerships 
    in a fair way. Typically, a matching game is defined by two sets of players 
    that each have preferences over at least some of the elements of the 
    other set. The objective of the game is then to find a mapping between the 
    sets of players in which everyone is happy enough with their match.
  doc_url: https://matching.readthedocs.io/
  dev_url: https://github.com/daffidwilde/matching

extra:
  recipe-maintainers:
    - mat333sp15
